neosTicaret/urls.py
from django.contrib import admin
from django.urls import path
from urunler.views import *
from kullanici.views import *

#veritabanindan gelen resimlerin goruntulenmesi icin gerekli importlar
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , index , name='index'),
    path('urun-detay/<int:urunId>' , product , name='urun'),
    path('kayit/' , kayit , name='register'),
    path('giris/' , giris , name='login'),
    path('cikis/' , cikis , name ='logout' ),
    path('olustur/' , olustur , name='olustur')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kullanici/models.py
from django.db import models

# Create your models here.

urunler/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Kategori(models.Model):
    isim = models.CharField(max_length=100)

    def __str__(self):
       return self.isim

class AltKategori(models.Model):
    isim = models.CharField(max_length=100)

    def __str__(self):
       return self.isim
    
class Tek(models.Model):
    isim = models.CharField(max_length=100)

    def __str__(self):
       return self.isim

class Urun(models.Model):
    satici = models.ForeignKey(User , on_delete=models.CASCADE , null=True)
    kategori = models.ForeignKey(Kategori , on_delete=models.SET_NULL , null=True)
    altkategori = models.ManyToManyField(AltKategori)
    seriNo = models.OneToOneField(Tek , on_delete = models.CASCADE , null=True , blank=True)
    isim = models.CharField(max_length=100)
    aciklama = models.TextField(max_length=1000)
    fiyat = models.IntegerField()
    resim = models.FileField(upload_to='urunler/', null=True) 

    def __str__(self):
       return self.isim

kullanici/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email' , 'password1' , 'password2' ]

    def __init__(self, *args , **kwargs):
        super(UserForm , self).__init__(*args , **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class' : 'form-control'})
            field.help_text = ''
        #self.fields['username'].widget.attrs.update({'class' : 'form-control'})    
            

urunler/forms.py
from django.forms import ModelForm
from .models import *

class UrunForm(ModelForm):
    class Meta:
        model = Urun
        fields = ['isim' , 'kategori' , 'altkategori' , 'aciklama' , 'fiyat' , 'resim']

    def __init__(self , *args , **kwargs):
        super(UrunForm , self).__init__(*args, **kwargs)
        for name , field in self.fields.items():
            field.widget.attrs.update({'class ' : 'form-control'})   

kullanici/views.py
from django.shortcuts import render , redirect
from .forms import *
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages

# Create your views here.
def kayit(request):
    form = UserForm()
    if request.method == 'POST':
     form = UserForm(request.POST)
     if form.is_valid():
        form.save()
        messages.success(request, 'Kullanici Olusturuldu')
        return redirect('index')
    context = {
        'form':form
    }
    return render(request , 'register.html' , context)

def giris(request):
   if request.method == 'POST':
      kullanici = request.POST['kullanici']
      sifre = request.POST['sifre']

      user = authenticate(request , username = kullanici , password = sifre)

      if user is not None:
         login(request, user)
         messages.success(request , 'Giris Yapildi')
         return redirect('index')
      else:
         messages.warning(request , 'Kullanici adi veya sifre hatali')
         return redirect ('login')
   return render(request , 'login.html')

   
def cikis(request):
   logout (request)
   messages.success(request , 'Cikis Yaildi')
   return redirect ('index')   

urunler/views.py
from django.shortcuts import render , redirect
from .models import *
from django.db.models import Q 
from django.contrib import messages
from .forms import *

# Create your views here.
def index(request):
    urunler = Urun.objects.all()
    kategoriler = Kategori.objects.all()
    search = ''
    if request.GET.get('search'):
        search = request.GET.get('search')
        urunler = Urun.objects.filter(
            Q(isim__icontains = search) |
            Q(aciklama__icontains = search) |
            Q(kategori__isim__icontains = search)
        )
    context = {
        'product':urunler,
        'search': search,
        'kategoriler':kategoriler
    } 
    return render(request , 'index.html' , context)

def product(request , urunId):
    urunum = Urun.objects.get(id = urunId)
    context = {
        'urun':urunum
    }
    return render(request , 'urun.html' , context)

def olustur(request):
    form = UrunForm()
    if request.method =='POST':
        form = UrunForm(request.POST , request.FILES)
        if form.is_valid():
            yeniUrun = form.save(commit = False)
            yeniUrun.satici = request.user
            yeniUrun.save()
            messages.success(request , 'Urun olusturuldu')
            return redirect('index')
        
    context = {
        'form':form
    }    
    return render (request , 'olustur.html' , context)

urunler/templates/includes/_footer.html
<footer class="mt-5 p-5 border">
    <h3 class="text-center p-5">Neos Ticaret</h3>
  </footer>

urunler/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-capitalize" href="#">{{request.user}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/cikis/">Cikis  Yap</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/olustur/">Olustur</a>
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link" href="/kayit/">Kayit Ol</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/giris/">Giris Yap</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Kategoriler
            </a>
            <ul class="dropdown-menu">
            {% for kategori in kategoriler  %}
            <li><a class="dropdown-item" href="/?search={{kategori.isim}}">{{kategori.isim}}</a></li>
            <ul >
               {% for i in kategori.urun_set.all  %}
                <li>{{i.isim}}</li>
               {% endfor %}
            </ul>
            {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search" method="GET"  action="/">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{search}}">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

urunler/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Anasayfa</title>
    {% endblock title %}


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body data-bs-theme="dark">
    {% include "includes/_navbar.html" %}

    {% if messages %}
    {% for mesaj in messages  %}
      <div class="alert alert-{{mesaj.tags}} text-center">
        {{mesaj}}
      </div>
    {% endfor %}
    {% else %}
    {% endif %}



      {% block content %}
      <div class="container mt-5">
        <div class="row">
          {% if product|length > 0 %}
          {% for urun in product  %}
          
          {% endfor %}
          {% else %}
          <h1>Eslesen urun bulunmamaktadir</h1>
          {% endif %}
            {% for urun in product  %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{urun.resim.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <h5 class="card-title">{{urun.isim}}</h5>
                        <p> Satici : {{urun.satici.username}}</p>
                      </div>
                      <p>{{urun.kategori.isim}}</p>
                      {% for alt in urun.altkategori.all  %}
                          <small>{{alt.isim}}</small>
                      {% endfor %}
                      <p class="card-text">{{urun.aciklama}}</p>
                      <p>Fiyat : {{urun.fiyat}} TL</p>
                      <a href="{% url 'urun' urun.id %}" class="btn btn-primary">Urunu incele</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
            </div>s
            </div>
      {% endblock content %}

      
     {% include "includes/_footer.html" %}
      








     





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

urunler/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block content %}
   <div class="container">
    <form action="" method="POST" class="w-50 m-auto border p-4">
        {% csrf_token %}
        <label for="">Kullanici Adi</label>
        <input type="text" name="kullanici" id="" class="form-control">
        <label for="">Sifre</label>
        <input type="password" name="sifre" id="" class="form-control">
        <input type="submit" value="Giris Yap" class="btn-btn">
    </form>
   </div>


{% endblock content %}

urunler/templates/olustur.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
   <div class="container">
    <form action="" method="POST" enctype="multipart/form-data" class="w-50 m-auto border p-4">
        {% csrf_token%}
        {{form}}
        <input type="submit" value="Olustur" class="btn btn-primary mt-2">
    </form>
   </div>

{% endblock content %}

urunler/templates/register.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<style>
    .helptext ul {
        padding: 0;
        list-style-type: none;
    }
    .errorlist{
        padding: 0;
        list-style-type: none;
        color: red;
    }
</style>




   <div class="container mt-5">
    <form action="" method="POST" class="w-50 m-auto border p-4">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Kayit Ol" class="btn btn-primary mt-2">
        
    </form>
   </div>

{% endblock content %}

urunler/templates/urun.html
{% extends "index.html" %}
{% load static%}

{% block title %}
    <title>Detay</title>
{% endblock title %}

      {% block content %}
      <div class="container">
        <div class="row">
            <div class="col-4">
                <img src="{{urun.resim.url}}" width="100%" alt="">
            </div>
            <div class="col-8">
                <h5>{{urun.isim}}</h5>
                <p>Kategori : {{urun.kategori.isim}}</p>
                <p>{{urun.aciklama}}</p>
                <p>{{urun.fiyat}}</p>
            </div>
        </div>
      </div>
      {% endblock content %}
      
{% comment %} extend de belırttıgımız sayfada block etıketı ıcerısınde belırledıgımız kkısmı degıstırmemzıı saglar
ınclude ıse Ş belırttıgımız dosyayı oldugu gıbı sayfaya ekler  {% endcomment %}